digite_algo = input('\033[7mDigite algo:\033[m ')
print(f'\nO tipo primitivo desse valor é \033[35m{type(digite_algo)}\033[m')
print(f'Só tem espaço? {digite_algo.isspace()}')
print(f'É um número? {digite_algo.isnumeric()}')
print(f'É alfabético? {digite_algo.isalpha()}')
print(f'É alfanumerico? {digite_algo.isalnum()}')
print(f'Esta em maiúscula? {digite_algo.isupper()}')
print(f'Esta em minúscula? {digite_algo.islower()}')
print(f'Esta capitalizada? {digite_algo.istitle()}')
